### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by luisfelipe3d** [pkp/docker-ojs#143]
Hi,
In commit https://github.com/pkp/docker-ojs/commit/afcc60ea2296bf248f9481a163a1fbb84e0df9e0, the package "supervisord" was removed but the configuration file of the package remains in the repository. It would be interesting to clean the repository in search of things that are no longer used to be removed.

Happy new year!
Cheers, 
Luis Leal.

**Comment by marcbria** [comment]
You are right Luis.

Thanks!
