### ISSUE TITLE
stable-3_3_0 is missing

### ISSUE THREAD

**Issue by luisfelipe3d** [pkp/docker-ojs#146]
The version stable-3_3_0 is missing on folder versions.

Luis Leal

**Comment by marcbria** [comment]
Don't ask me why, but at certain point 3_3_0 was removed.
When I checked it and I found issues with 3.1.2-4 (wrong php version), two stable missing (3_2_0 and 3_1_2) and one stable added but don't exist yet (3_3_1).

fixed but still not pushed to DockerHub.

**Comment by luisfelipe3d** [comment]
Here everything is fine the issue was solved on commit b1be00764ce3c2196529ffcfda26e1cc70e16ea5.  
I'll close this issue!
