### ISSUE TITLE
OJS - Building local images Error

### ISSUE THREAD

**Issue by wi-mma** [pkp/docker-ojs#155]
Hello,

I have a problem to "Building local images" from the code introduction. I tried the statement (in my terminal): "docker build -t local/ojs:3_2_0-1 ." in the folder /versions/3_2_0-1/alpine/apache/php73 but I get the error in the picture.

If somebody could help me, I would appreciate it.

<img width="1440" alt="Error" src="https://user-images.githubusercontent.com/99693601/156939846-ada87df7-3bb2-4542-a5ef-36ea520503d3.png">

**Comment by luisfelipe3d** [comment]
Hi @wi-mma,

The easy way to solve your problem is **change npm to yarn**:
``` bash
ENV BUILDERS \
        git  \
        nodejs \
        yarn
```
and 
`yarn && yarn run build `

Cheers,
Luis Leal.

**Comment by marcbria** [comment]
@wi-mma do you mind to confirm that updating the npm did the job?
If not, did the problem disappears moving to yarn?

Thanks for your feedback,
m.
