### ISSUE TITLE
Default captcha font is not available

### ISSUE THREAD

**Issue by lucasdiedrich** [pkp/docker-ojs#19]
The default captcha font (FreeSerif) is not provided in container, so the captcha is not generated corretly. 

To fix:
1. apk add ttf-freefont
2. ln -s /usr/share/fonts/TTF/FreeSerif.ttf /usr/share/fonts/FreeSerif.ttf

Probably going to send an PR with this fix.

**Comment by lucasdiedrich** [comment]
@marcbria

**Comment by marcbria** [comment]
Hi Lucas. Thanks for the issue, but don't waste your time in a PR for this. I'm doing it right now.

If you have some time, take a general review of the docker file and tell us what you think and how to improve it... or take a look to the nginx branch that need to be fixed. ;-)

**Comment by lucasdiedrich** [comment]
Hey @marcbria , the PR is already made: https://github.com/pkp/docker-ojs/pull/20

But yes, there is some things i want to fix also, like supervisorctl is not working properly. going to check it out.

thanks.

**Comment by marcbria** [comment]
Even it was fixed, I forget to close this issue. 
Doing it (a year after) to keep the issue list up to date.
