### ISSUE TITLE
The password of database user ojs is wrong! 

### ISSUE THREAD

**Issue by angelochu7** [pkp/docker-ojs#21]
Hi,
I just would like to drop a line for the captioned issue. The password of database user ojs should be **ojs** instead of **ojsPwd** specified in the README file. I verified this by opening the environment variable .env file located in the \docker-ojs-master\versions\3_2_0-3\alpine\apache\php73

By the way, thanks for the ojs docker!

**Comment by marcbria** [comment]
Hi @angelochu7 

Sorry a lot for the delay in this answer. 

You are right... Pwd was changed in the template but not updated in the README.
Changing it all right now.

Cheers,
m.
