### ISSUE TITLE
Commit for 3_3_0-10 missing?

### ISSUE THREAD

**Issue by SydneyUni-Jim** [pkp/docker-ojs#223]
In the main branch, I don't see a version directory for 3_3_0-10 (#158). The last I see is for 3_3_0-9.

**Comment by marcbria** [comment]
We are testing gitLab CI/CD tools for auto build the docker images os images are now built here:
https://gitlab.com/pkp-org/docker/ojs

Images are also pushed to gitHub.

PD: We will probably finish in gitHub Actions so we will probably come back to this repo soon.
