### ISSUE TITLE
3.3.0 still on Alpine 3.11

### ISSUE THREAD

**Issue by SydneyUni-Jim** [pkp/docker-ojs#224]
With commits 73fbfaee59b855dbbc3dbed1b24b5142d642e85d and 7be2fd81c2e5a81c779f7d5bcff0033e55cd0f43, Alpine updates from 3.13.6 to 3.14 for OJS 3.0.0 to 3.1.2-4. Meanwhile 3.2.0-0 onwards, latest, main and stable-* are still at Alpine 3.11.

**Comment by marcbria** [comment]
In #159 we are talking about how to refactor this project.
The consensus now is old versions won't be updated with security patches, as far as they won't be used for production sites.
Only last stable and LTS will be keep up to date.

We are still designing how it need to be so if you have arguments to defend that more images need to be updated is a good moment explain it.

**Comment by SydneyUni-Jim** [comment]
I'm not sure I'm following because the older versions of OJS (3.0.0 to 3.1.2-4) have moved to Alpine 3.14, while the newer versions of OJS are still on Alpine 3.11.

**Comment by SydneyUni-Jim** [comment]
Might the Dockerfile templates might be erroneous?

`Dockerfile-alpine-apache-php70.template` uses alpine:3.14, which installs PHP 7.4.
`Dockerfile-alpine-apache-php73.template` and `Dockerfile-alpine-apache-php74.template` both use alpine:3.11, which installed PHP 7.3.

alpine:3.11 doesn't have `/etc/php/7.3` or `/etc/php/7.4` directories, as far as I can see. I only see `/etc/php7`.

**Comment by SydneyUni-Jim** [comment]
It looks like alpine:3.12 was the last to install PHP 7.3.

**Comment by marcbria** [comment]
Ok. I understood it in the opposite way... and you are right: It didn't make any sense.
It will be fixed soon.

**Comment by marcbria** [comment]
Fixed... but not tested yet.
ReBuilding 3.3.0-11 with this fix and the iconv issue.
