### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by szitnik** [pkp/docker-ojs#25]
Hey, 

thanks for preparing eveything. I would like to update our existing OJS installation to docker version. When is the plan to say this repo could be used in production environment?

Thanks for the answer!
Slavko

**Comment by marcbria** [comment]
Hi @szitnik 

Sorry a lot for the delay in this answer.
The project is used in production environments right now, but we are not able to offer full support so this is why we don't recommend it.

More people use it, better feedback we will get and more solid will it be... so feel free to join our "early adopters" group.

Cheers,
m.

**Comment by szitnik** [comment]
Thanks a lot - I thought there are some known fixes to be done until the final version.
