### ISSUE TITLE
About Encoding

### ISSUE THREAD

**Issue by acuartango** [pkp/docker-ojs#26]
Hi,
I have an OJS installation in a virtual machine and i want to migrate to a docker container.

I've new install ojs 2.4.8.5 from docker image.

Then i have done a backup of my installation's database and i have migrated to the mariadb container. 

I've ensured the encoding of my database, tables and text fields is UTF-8.

When i access to my installation on the container i see all the spanish accents bad encoded.

In the config.inc.php (locale section) i have :

;;;;;;;;;;;;;;;;;;;;;;;;;
; Localization Settings ;
;;;;;;;;;;;;;;;;;;;;;;;;;

[i18n]

; Default locale
locale = es_ES

; Client output/input character set
client_charset = utf-8

; Database connection character set
; Must be set to "Off" if not supported by the database server
; If enabled, must be the same character set as "client_charset"
; (although the actual name may differ slightly depending on the server)
connection_charset = utf8

; Database storage character set
; Must be set to "Off" if not supported by the database server
database_charset = utf8

; Enable character normalization to utf-8
; If disabled, strings will be passed through in their native encoding
; Note that client_charset and database collation must be set
; to "utf-8" for this to work, as characters are stored in utf-8
; (Note that this is generally no longer needed, as UTF8 adoption is good.)
charset_normalization = Off

It works ok when i change client_charset  to iso-8859-1 : 

;;;;;;;;;;;;;;;;;;;;;;;;;
; Localization Settings ;
;;;;;;;;;;;;;;;;;;;;;;;;;

[i18n]

; Default locale
locale = es_ES

; Client output/input character set
client_charset = iso-8859-1
;client_charset = utf-8

; Database connection character set
; Must be set to "Off" if not supported by the database server
; If enabled, must be the same character set as "client_charset"
; (although the actual name may differ slightly depending on the server)
connection_charset = utf8

; Database storage character set
; Must be set to "Off" if not supported by the database server
database_charset = utf8

; Enable character normalization to utf-8
; If disabled, strings will be passed through in their native encoding
; Note that client_charset and database collation must be set
; to "utf-8" for this to work, as characters are stored in utf-8
; (Note that this is generally no longer needed, as UTF8 adoption is good.)
charset_normalization = Off

I have see that this version of mariadb default-character-set  is latin1 by default doing:
show global variables;

I have changed docker-compose file adding to database definition (i don't know if is the best way to do this):
      command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']

I can now see all accents perfectly  encoded without seeing "iso-8859-1" at "client_charset" on the config.inc.php file inside the container.

¿Do you think it would be better to give the containers database definition in more international UTF-8 encoding? Or it could be mentioned in the README people to know how to set utf8 in all places (database, connection, tables, fields, files...)

Thanks for the great job!

**Comment by marcbria** [comment]
Hola @acuartango,

Disculpa la demora. Tenemos los issues de este proyecto algo abandonados. Nos ponemos con ello.

Si no te importa, aprovecho y te escribo en español que es mi lengua nativa.

Los charsets son siempre un drama. Mi recomendación, si no estabas trabajando ya con utf8, es aprovechar que vas a hacer un dump de la BD para migrar de latin an utf8. [En concreto utf8mb4_unicode_ci](https://crondev.blog/2018/09/16/mysql-charset-collation-recommendations/).

Además, también es un buen momento para unificar motores de BD y migrar a InnoDB, que ya tiene un rendimiento igual o superior a MyISAM y es la opción recomendada por PKP.

Para ello, si el dump que tienes te respeta la codificación (ves bien los acentos ¿no?) puedes hacer un simple search&replace (sed, awk, pie...) del motor y de los charsets y entregar ese dump al docker para que te lo cargue automáticamente en tu mariaDB cuando cree el contenedor.

Cualquier cosa, escribe por aquí.

Un saludo,
m.

**Comment by acuartango** [comment]
Gracias Marc!
Lo que yo quería aportar era un cambio al docker-compose.yml

El problema no es de OJS, es de MariaDB que por defecto tiene en el parámetro "default-character-set" como  "latin1":
https://mariadb.com/kb/en/setting-character-sets-and-collations

La prueba que he hecho es importar una BD con todo en UTF8 en el contenedor de mariadb. Pero si luego en el config.inc.php del contenedor de OJS pongo "utf-8" al parámetro "client_charset", veo mal las tildes. Si pongo "iso-8859-1" veo las tildes perfectamente.

Si a la definición del contenedor de **mariadb** en el **docker-compose** le añado la línea:
command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']

Entonces importando exactamente la misma base de datos del mismo modo y dejando el parámetro "client_charset" del config.inc.php a "utf-8", entonces sí que visualizo correctamente las tildes.

Por eso aportaba el comentario para cambiar el docker-compose en la parte de mariadb, por si puede ayudar, ya que así el comportamiento por defecto de la BD si se usa utf8 sería coherente con la configuración de OJS.

En cualquier caso es un cambio que cualquiera puede hacer sin problemas, por eso comentaba que quizás no hacía falta modificar el docker-compose pero se podría dejar comentado con una breve explicación, bien en el docker-compose  con un comentario, bien en el README.

En cualquier caso muchísimas gracias por el trabajo que habéis aportado a todos.

un saludo,
aitor

**Comment by marcbria** [comment]
Ah... pues disculpa. No te había entendido y creo que tienes razón. :-)

Aunque tengo dudas sobre si añadir el comando que propones puede tener efectos en el comportamiento del contenedor.
¿Has probado si con ese cambio el entrypoint sigue funcionando?

Aunque en realidad, ya ofrecemos una solución para cambiar el charset que consiste en des-comentar esta línea:
https://github.com/pkp/docker-ojs/blob/7bbe96b59b3b15e70bc38658d14f11fd62d68092/versions/3_2_1-4/alpine/apache/php73/docker-compose.yml#L27

¿Tal vez deberíamos explicar mejor esta parte en el README?

Sea como sea, tu propuesta me gusta pq. todo seguiría funcionando con un simple docker-compose (y luego si quieres puedes ir creando volúmenes para configurar a tu gusto, dar persistencia, añadir complejidad, etc...) pero por otro lado, ofrecer el docker-compose con el volumen de configuración del charset descomentado por defecto tampoco sería mala opción...

BTW, debería ser utf8mb4_* ¿no?

Un saludo,
m.

**Comment by acuartango** [comment]
Hola,
sí que he probado (me ha regenerado el contenedor y he tenido que volver a hacer el volcado de nuestro entorno de prepro) y el entry point sigue funcionando.

Lo de utf8mb4, claro, totalmente de acuerdo. He usado utf8 por costumbre... pero para un contenedor público que se puede usar en cualquier idioma, mejor utf8mb4.

Y la opción que me gusta más es la que dices de dejar descomentado por defecto el charset y dejar por defecto utf8mb4. En cualquier caso aclarar más lo de los encodings en el README sería genial. Es una de las cosas que más dolores de cabeza suele dar a los que empiezan.

Gracias por todo, un magnífico trabajo !

**Comment by marcbria** [comment]
Gracias.

Si te animas a hacer un PR, lo acepto y palante.
Si no... a la vuelta de semana santa lo incorporo.
