### ISSUE TITLE
bug in ojs-upgrade

### ISSUE THREAD

**Issue by edelm** [pkp/docker-ojs#299]
I think there is a bug in the ojs-upgrade script which prevents setting "installed=On" in the config.inc.php.

Here is the link to the line containing the bug:
https://github.com/pkp/docker-ojs/blob/561c442e0179f224939bf83a7298da8da42a49e6/versions/stable-3_3_0/alpine/apache/php73/root/usr/local/bin/ojs-upgrade#L14

I guess it should be:
```
sed -i '/^installed/c\installed = On' /tmp/config.inc.php
```

**Comment by marcbria** [comment]
You are right.
Changed in gitLab (that is where I'm working till we refactor this project).

https://gitlab.com/pkp-org/docker/ojs
