### ISSUE TITLE
How to remove portnumer from url.

### ISSUE THREAD

**Issue by ShubashBiswas** [pkp/docker-ojs#345]
Dear OJS Team

I am testing docker-ojs on locally. The installation was smooth. But i am not able to remove port number from the URL. I am using [jc21/nginx-proxy-manager](https://hub.docker.com/r/jc21/nginx-proxy-manager) as reverse proxy for my other port removal. But as docker-ojs  currently on Apache2 nginx-proxy-manager is not useful in docker-ojs. I am not a coding person. 

Please let me know how to achieve the url without port number.

**Comment by marcbria** [comment]
Hi @ShubashBiswas 

I'm sorry but I don't use NPM myself (I prefer traefik) and I can give you any advice about how to set it up.
Anyway, this project is about the docker-ojs container, not how to setup a reverse proxy so I suggest you to ask for help in the NPM project: https://github.com/NginxProxyManager/nginx-proxy-manager

If you have specific questions about the docker container, feel free to open a new issue.

Cheers,
m.
