### ISSUE TITLE
Upgrade exclude list (or pull it from pkp's)

### ISSUE THREAD

**Issue by marcbria** [pkp/docker-ojs#35]
PKP's build script includes a variable with an "exclude list" that lists all the files and folders that need to be removed to package.
This list was recently changed to fix an issue with "example" folders:
https://github.com/pkp/ojs/commit/c2d3effae6748087b4a506f47433bece14d3b4dd

We have 2 options here:
1. The fast&easy one: Modify our exclude.list file to sync with pkp's one.
2. The definitive: Ask pkp to keep this as an external file, so we can pull it during Dockerfile run.

I think we can apply 1 and commit a PR with 2 for PKP consideration.

**Comment by asmecher** [comment]
Are you proposing to take the current exclusion list (which is embedded in the build script) and move it to e.g. a `.txt` file in the same repository? I'd support that.

**Comment by marcbria** [comment]
Yes Alec, this was the intention.

> Alec, if you like I can make a new attempt next week or so.

Get ready for a new PR... ;-)
