### ISSUE TITLE
HTTPS reverse proxy requires "PassENV HTTPS" on VirtualHost *:80

### ISSUE THREAD

**Issue by frafra** [pkp/docker-ojs#41]
I just wanted to document this workaround for `/etc/apache2/conf.d/ojs.conf` in case a reverse proxy with SSL offloading is used. `PassENV HTTPS` should be added to the first VirtualHost, on port 80.

**Comment by marcbria** [comment]
Thanks for the workaround Francesco.

If you add this somewhere in the readme.md and send us a PR we will happily merge it.

Happy to see the images are working fine to you.

Cheers,
m.

**Comment by frafra** [comment]
@juanCure your question is related to how container works, more than OJS: even if changing the configuration file inside a running container would work (which it would not, since you would also need to reload the web server), it would not be very useful, since the change would not be persistent (the container will be recreated/restarted sooner or later).
Making changes persistent in a container requires modifying the Dockerfile or mounting the custom configuration file. Ideally, OJS should handle this case without any change, but this is not the case, since there is only a suggestion in the README file.
