### ISSUE TITLE
Version ojs:3_3_0-7 - Add reviewer mail

### ISSUE THREAD

**Issue by szitnik** [pkp/docker-ojs#45]
Dear all,

I am using docker-based OJS, version ojs:3_3_0-7 and have problems as mails when I click "Add reviewer" are not sent, so reviewer is not notified about a new review.

In the Web interface I get mail successfully sent notification and also there are no errors in error.log.

Does anyone know about this problem?

Slavko

**Comment by szitnik** [comment]
I have just found the problem. If I uncheck option "Include a secure link in the email invitation to reviewers." then sending to reviewers is working. But still I do not know what is the problem is option is checked (maybe I just missed something in the config or documentation).

**Comment by marcbria** [comment]
Sorry for the delay in this answer @szitnik.

This repo is just for the docker image of OJS, so we only visit it from time to time.

If you need help about OJS, you need to post in pkp's community forum (that by the way, is huge):
https://forum.pkp.sfu.ca/

Cheers,
m.
